name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: gcc
      run: |
       gcc Abhinav/insertion.c
       ./a.out
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
